---
- hosts: all
  become: yes
  tasks:
    - name: Install Apache
      yum: 
        name: httpd
        state: latest
    - name: git checkout the website
      git:
        dest: /var/www/html
        repo: https://github.com/insighttechworld/content-webserver-ansible.git
